#!/bin/bash
# prints total portfolio value from current stock price and number of shares

DATA=~/utils/stocks-data/portfolio
TOTAL=0

# get tickers and number of shares
while read ENTRY; do
    TICKER=$(echo $ENTRY | awk '{printf $1}')
    SHARES=$(echo $ENTRY | awk '{printf $2}')
    # get current price from yahoo
    PRICE=$(curl -s "https://finance.yahoo.com/quote/$TICKER?ltr=1" | grep -Eo "data-reactid=\"5(0|5)\">.{0,8}</span>" | grep -Eo "[0-9]+([.][0-9]+)?" | tr "\n" " " | awk '{printf "%s\n", $NF}')
    echo "$TICKER $PRICE" | awk '{printf "%s $%'\''.2f\n", $1, $2}'
    # running total
    TOTAL=$(echo "$TOTAL + $SHARES * $PRICE" | bc)
done < $DATA

# format total
echo $TOTAL | awk '{printf "$%'\''.2f\n", $1}'
